Answers on questions
Andex/TestGuru pull request #10
Opened 2021-01-13 21:13 UTC by Andex

2021-01-14 06:14 UTC, BubuntuClu requested changes

2021-01-14 06:14 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body, :correct, :question_id)
question_id тут не нужен. ты черз ассоциацию создаешь ответ

2021-01-14 06:14 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :set_test, only: %i[new create index]
было лучше на мой взгляд. find_question, find_test в одном стиле названы. а set уже выбивается

2021-01-14 06:14 UTC, BubuntuClu commented on app/helpers/test_passages_helper.rb
> +    100 / test_passage.test.questions.count * test_passage.correct_questions
это больше походит на метод модели

2021-01-14 06:14 UTC, BubuntuClu commented on app/views/test_passages/result.html.erb
> +  <% if result >= 85 %>
что такое 85? магическое число, которое без контекста не понять. вынеси ее в модель в константу и обзови понятно
выражение в if можно заменить на метод success? у пассажа, в нем делать эту проверку. и хэлпер уйдет в модель

2021-01-14 06:52 UTC, Andex commented on app/helpers/test_passages_helper.rb
> +    100 / test_passage.test.questions.count * test_passage.correct_questions
Как определить куда больше подходит метод - в модель или в хелпер? Для меня не всегда очевидно.

2021-01-14 06:57 UTC, Andex commented on app/views/test_passages/result.html.erb
> +  <% if result >= 85 %>
Я думала о том, чтобы здесь возвращать true\false, но тогда нужно будет дополнительно вытаскивать **цифру процента** прохождения теста для отображения зеленым\красным.

2021-01-14 11:35 UTC, BubuntuClu commented on app/helpers/test_passages_helper.rb
> +    100 / test_passage.test.questions.count * test_passage.correct_questions
которые нужны для отрисовки. тут у тебя чистая логика, ни как html не задействован

2021-01-14 11:36 UTC, BubuntuClu commented on app/views/test_passages/result.html.erb
> +  <% if result >= 85 %>
можешь закэшировать число в получении процентов через `@percent ||=` и во вьюхе вызывать метод, который у тебя подсчитывает процент. из-за того что процент у тебя считается в методе success? у тебя уже будет значение и не будет доп подсчетов

2021-01-14 11:37 UTC, BubuntuClu commented on app/views/test_passages/result.html.erb
> +  <% if result >= 85 %>
ну и метод подсчета надо вынести из `success?` так он тебе отдельно тоже нужен

2021-01-14 12:31 UTC, merged

2021-01-17 11:01 UTC, Andex commented
1. Сделать назначение следующего вопроса в модели TestPassage с помощью обратного вызова
2. Доработать шаблон результата прохождения теста:
Выводить сообщение и процент успеха в зависимости от количества правильных ответов
Если процент успеха >= 85% число должно быть зелёного цвета и сообщение должно говорить об успешном прохождении теста
Если процент успеха < 85% число должно быть красного цвета и сообщение должно говорить о том что тест не пройден
Добавить навигацию в виде ссылки на список всех тестов
3. Доработать шаблон отображения прохождения теста:
Выводить номер текущего вопроса и общее количество вопросов теста